var prettyName = require('../index');

describe('General', function() {
	it('can make pretty names', function() {
		expect(prettyName('Andy Warhol')).toEqual('Andy Warhol');
		expect(prettyName('Maurice Le Scouezec')).toEqual('Maurice Le Scouezec');
		expect(prettyName('Philip-Lorca Dicorcia')).toEqual('Philip-Lorca Dicorcia');
		expect(prettyName('Peter Le Cave')).toEqual('Peter Le Cave');
		expect(prettyName('James Le Jeune')).toEqual('James Le Jeune');
		expect(prettyName('Fernand Allard-L\'Olivier')).toEqual('Fernand Allard-L\'Olivier');
		expect(prettyName('Angelo del Bon')).toEqual('Angelo del Bon');
		expect(prettyName('Max Le Verrier')).toEqual('Max Le Verrier');
		expect(prettyName('Hans Am Ende')).toEqual('Hans Am Ende');
		expect(prettyName('Angelo Dall\'Oca Bianca')).toEqual('Angelo Dall\'Oca Bianca');
		expect(prettyName('d\'Arcy Doyle')).toEqual('d\'Arcy Doyle');
		expect(prettyName('Alain Le Yaouanc')).toEqual('Alain Le Yaouanc');
		expect(prettyName('Park Seo-Bo')).toEqual('Park Seo-Bo');
		expect(prettyName('De Simone')).toEqual('De Simone');
		expect(prettyName('Karl O\'Lynch van Town')).toEqual('Karl O\'Lynch van Town');
		expect(prettyName('Van de Velde')).toEqual('Van de Velde');
		expect(prettyName('Yu Fei\'An')).toEqual('Yu Fei\'An');
		expect(prettyName('Henry Le Jeune')).toEqual('Henry Le Jeune');
		expect(prettyName('Adrien Le Mayeur')).toEqual('Adrien Le Mayeur');
		expect(prettyName('Frans Pieter ter Meulen')).toEqual('Frans Pieter ter Meulen');
		expect(prettyName('Marcello Lo Giudice')).toEqual('Marcello Lo Giudice');
		expect(prettyName('Cesare Felix Georges dell\'Acqua')).toEqual('Cesare Felix Georges dell\'Acqua');
		expect(prettyName('Richard di Rosa')).toEqual('Richard di Rosa');
		expect(prettyName('Alcide Le Beau')).toEqual('Alcide Le Beau');
		expect(prettyName('Loic Le Groumellec')).toEqual('Loic Le Groumellec');
		expect(prettyName('Pierre Le Boeuff')).toEqual('Pierre Le Boeuff');
		expect(prettyName('Hendrik Gerrit ten Cate')).toEqual('Hendrik Gerrit ten Cate');
		expect(prettyName('Edward Le Bas')).toEqual('Edward Le Bas');
		expect(prettyName('Frederick Timpson L\'Ons')).toEqual('Frederick Timpson L\'Ons');
		expect(prettyName('Thorvald Hagedorn-Olsen')).toEqual('Thorvald Hagedorn-Olsen');
		expect(prettyName('Jean Jacques Le Barbier the Elder')).toEqual('Jean Jacques Le Barbier the Elder');
		expect(prettyName('David French Le Roy')).toEqual('David French Le Roy');
		expect(prettyName('Ivan Le Lorraine Albright')).toEqual('Ivan Le Lorraine Albright');
		expect(prettyName('Jean Le Gac')).toEqual('Jean Le Gac');
		expect(prettyName('Van Balen')).toEqual('Van Balen');
		expect(prettyName('Jun\'Ichiro Sekino')).toEqual('Jun\'Ichiro Sekino');
		expect(prettyName('Van Os')).toEqual('Van Os');
		expect(prettyName('De Heem')).toEqual('De Heem');
		expect(prettyName('Kim Ki-Chang')).toEqual('Kim Ki-Chang');
		expect(prettyName('John Le Capelain')).toEqual('John Le Capelain');
		expect(prettyName('Eustache Le Sueur')).toEqual('Eustache Le Sueur');
		expect(prettyName('Pierre Le Trividic')).toEqual('Pierre Le Trividic');
		expect(prettyName('Georgina M de L\'Aubiniere')).toEqual('Georgina M de L\'Aubiniere');
		expect(prettyName('Johannes Marinus ten Cate')).toEqual('Johannes Marinus ten Cate');
		expect(prettyName('Roberto Sebastian Matta Echaurren')).toEqual('Roberto Sebastian Matta Echaurren');
		expect(prettyName('Gustave Edouard Le Senechal de Kerdreoret')).toEqual('Gustave Edouard Le Senechal de Kerdreoret');
		expect(prettyName('Abdel Hadey el-Gazzar')).toEqual('Abdel Hadey el-Gazzar');
		expect(prettyName('Louay Kayyali')).toEqual('Louay Kayyali');
		expect(prettyName('Van Huysum')).toEqual('Van Huysum');
		expect(prettyName('Jean Le Merdy')).toEqual('Jean Le Merdy');
		expect(prettyName('Robert de Niro Sr.')).toEqual('Robert de Niro Sr.');
		expect(prettyName('Claude Le Sauteur')).toEqual('Claude Le Sauteur');
		expect(prettyName('Atelier van Lieshout')).toEqual('Atelier van Lieshout');
		expect(prettyName('Van Bloemen')).toEqual('Van Bloemen');
		expect(prettyName('Victor Viollet Le Duc')).toEqual('Victor Viollet Le Duc');
		expect(prettyName('Paul Le More')).toEqual('Paul Le More');
		expect(prettyName('Chun Kyung-Ja')).toEqual('Chun Kyung-Ja');
		expect(prettyName('Robert Le Berger')).toEqual('Robert Le Berger');
		expect(prettyName('Dirk van Erp')).toEqual('Dirk van Erp');
		expect(prettyName('Frank Le Gall')).toEqual('Frank Le Gall');
		expect(prettyName('Joseph Le Guluche')).toEqual('Joseph Le Guluche');
		expect(prettyName('Walter Williams (1920 - 1988)')).toEqual('Walter Williams (1920 - 1988)');
		expect(prettyName('Pierre Thomas Le Clerc')).toEqual('Pierre Thomas Le Clerc');
		expect(prettyName('De Momper')).toEqual('De Momper');
		expect(prettyName('Reuben Le Grand Johnston')).toEqual('Reuben Le Grand Johnston');
		expect(prettyName('Jean Pierre Le Boulch')).toEqual('Jean Pierre Le Boulch');
		expect(prettyName('John la Farge')).toEqual('John la Farge');
		expect(prettyName('Kwon Ok-Yeon')).toEqual('Kwon Ok-Yeon');
		expect(prettyName('Andre L\'Archeveque')).toEqual('Andre L\'Archeveque');
		expect(prettyName('Ingalvur Av Reyni')).toEqual('Ingalvur Av Reyni');
		expect(prettyName('Silvano d\'Ambrosio')).toEqual('Silvano d\'Ambrosio');
		expect(prettyName('Qiu de Shu')).toEqual('Qiu de Shu');
		expect(prettyName('Suh Se-Ok')).toEqual('Suh Se-Ok');
		expect(prettyName('Choi Wook-Kyung')).toEqual('Choi Wook-Kyung');
		expect(prettyName('Jean Louis Le Toullec')).toEqual('Jean Louis Le Toullec');
		expect(prettyName('Josep Riera I Arago')).toEqual('Josep Riera I Arago');
		expect(prettyName('Omar el-Nagdi')).toEqual('Omar el-Nagdi');
		expect(prettyName('Mohammed Ben Ali R\'Bati')).toEqual('Mohammed Ben Ali R\'Bati');
		expect(prettyName('Aleksandr Evgen\'Evich Iakovlev')).toEqual('Aleksandr Evgen\'Evich Iakovlev');
		expect(prettyName('Aarnout ter Himpel')).toEqual('Aarnout ter Himpel');
		expect(prettyName('Van der Meulen')).toEqual('Van der Meulen');
		expect(prettyName('Ra\'Anan Levy')).toEqual('Ra\'Anan Levy');
		expect(prettyName('Melanie Le Brocquy')).toEqual('Melanie Le Brocquy');
		expect(prettyName('De Vos')).toEqual('De Vos');
		expect(prettyName('Van Lint')).toEqual('Van Lint');
		expect(prettyName('Attributed to Pierre-Paul Prud\'Hon')).toEqual('Attributed to Pierre-Paul Prud\'Hon');
		expect(prettyName('Adel el-Siwi')).toEqual('Adel el-Siwi');
		expect(prettyName('Ernest Le Villain')).toEqual('Ernest Le Villain');
		expect(prettyName('Tommaso d\'Antonio Manzuoli')).toEqual('Tommaso d\'Antonio Manzuoli');
		expect(prettyName('Su-En Wong')).toEqual('Su-En Wong');
		expect(prettyName('Bernardus Gerardus ten Berge')).toEqual('Bernardus Gerardus ten Berge');
		expect(prettyName('Jacques Le Moyne')).toEqual('Jacques Le Moyne');
		expect(prettyName('Pieter ten Cate')).toEqual('Pieter ten Cate');
		expect(prettyName('Francois van den Berghe')).toEqual('Francois van den Berghe');
		expect(prettyName('Kwon Young-Woo')).toEqual('Kwon Young-Woo');
		expect(prettyName('Djanira da Motta E Silva')).toEqual('Djanira da Motta E Silva');
		expect(prettyName('Jean Baptiste Le Paon')).toEqual('Jean Baptiste Le Paon');
		expect(prettyName('Olivier Le May')).toEqual('Olivier Le May');
		expect(prettyName('Studio Bbpr')).toEqual('Studio Bbpr');
		expect(prettyName('Leslie van der Sluys')).toEqual('Leslie van der Sluys');
		expect(prettyName('Yim Jik-Soon')).toEqual('Yim Jik-Soon');
		expect(prettyName('Choi Young-Rim')).toEqual('Choi Young-Rim');
		expect(prettyName('Abdellatif Ala-el-Din')).toEqual('Abdellatif Ala-el-Din');
		expect(prettyName('Hubert Le Gall')).toEqual('Hubert Le Gall');
		expect(prettyName('Jules Le Ray')).toEqual('Jules Le Ray');
		expect(prettyName('Van Ostade')).toEqual('Van Ostade');
		expect(prettyName('Van Stry')).toEqual('Van Stry');
		expect(prettyName('Ugo la Pietra')).toEqual('Ugo la Pietra');
		expect(prettyName('Jan Chin-Shuei')).toEqual('Jan Chin-Shuei');
		expect(prettyName('Liu de Liu')).toEqual('Liu de Liu');
		expect(prettyName('Follower of Pierre-Paul Prud\'Hon')).toEqual('Follower of Pierre-Paul Prud\'Hon');
		expect(prettyName('Fernand Le Quesne')).toEqual('Fernand Le Quesne');
		expect(prettyName('Van Kessel')).toEqual('Van Kessel');
		expect(prettyName('Jacques Le Chevallier')).toEqual('Jacques Le Chevallier');
		expect(prettyName('Herman Henri Op der Heyde')).toEqual('Herman Henri Op der Heyde');
		expect(prettyName('Van Noort')).toEqual('Van Noort');
		expect(prettyName('Ha In-Doo')).toEqual('Ha In-Doo');
		expect(prettyName('Henry Le Monnier')).toEqual('Henry Le Monnier');
		expect(prettyName('Nerone E Patuzzi')).toEqual('Nerone E Patuzzi');
		expect(prettyName('Dominique Adolphe Grenet de Joigny')).toEqual('Dominique Adolphe Grenet de Joigny');
		expect(prettyName('Jan Le Ducq')).toEqual('Jan Le Ducq');
		expect(prettyName('Qiu Jiongjiong')).toEqual('Qiu Jiongjiong');
		expect(prettyName('Gaston la Touche')).toEqual('Gaston la Touche');
		expect(prettyName('Jean Le Guennec')).toEqual('Jean Le Guennec');
		expect(prettyName('Aref el-Rayess')).toEqual('Aref el-Rayess');
		expect(prettyName('Follower of Eustache Le Sueur')).toEqual('Follower of Eustache Le Sueur');
		expect(prettyName('Krishnaji Howlaji Ara')).toEqual('Krishnaji Howlaji Ara');
		expect(prettyName('Andrea de Zerega')).toEqual('Andrea de Zerega');
		expect(prettyName('Christian Le Moult')).toEqual('Christian Le Moult');
		expect(prettyName('Hung Jui-Lin')).toEqual('Hung Jui-Lin');
		expect(prettyName('Rene Le Forestier')).toEqual('Rene Le Forestier');
		expect(prettyName('Hwang Yeom-Soo')).toEqual('Hwang Yeom-Soo');
		expect(prettyName('Oscar de Las Flores')).toEqual('Oscar de Las Flores');
		expect(prettyName('Qin da Hu')).toEqual('Qin da Hu');
		expect(prettyName('Salomon Le Tropezien')).toEqual('Salomon Le Tropezien');
		expect(prettyName('Luca Dall\'Olio')).toEqual('Luca Dall\'Olio');
		expect(prettyName('Attributed to Jean Jacques Le Barbier the Elder')).toEqual('Attributed to Jean Jacques Le Barbier the Elder');
		expect(prettyName('Andre Guerin Le Guay')).toEqual('Andre Guerin Le Guay');
		expect(prettyName('Issam el-Said')).toEqual('Issam el-Said');
		expect(prettyName('Quac In-Sik')).toEqual('Quac In-Sik');
		expect(prettyName('Lucia Ponga degli Ancillo')).toEqual('Lucia Ponga degli Ancillo');
		expect(prettyName('Khaled Ben Slimane')).toEqual('Khaled Ben Slimane');
		expect(prettyName('Hemingway, Ernest.')).toEqual('Hemingway, Ernest.');
		expect(prettyName('Van Cleve')).toEqual('Van Cleve');
		expect(prettyName('Friso ten Holt')).toEqual('Friso ten Holt');
		expect(prettyName('Gabriele de Santis')).toEqual('Gabriele de Santis');
		expect(prettyName('Georges Le Meilleur')).toEqual('Georges Le Meilleur');
		expect(prettyName('Van Cleef')).toEqual('Van Cleef');
		expect(prettyName('Vicente Do Rego Monteiro')).toEqual('Vicente Do Rego Monteiro');
		expect(prettyName('Bruce Le Dain')).toEqual('Bruce Le Dain');
		expect(prettyName('Stanislas Batowski-Kaczor')).toEqual('Stanislas Batowski-Kaczor');
		expect(prettyName('Donald Vogel')).toEqual('Donald Vogel');
		expect(prettyName('Avaf (Assume Vivid Astro Focus)')).toEqual('Avaf (Assume Vivid Astro Focus)');
		expect(prettyName('Eugene Viollet-Le-Duc')).toEqual('Eugene Viollet-Le-Duc');
		expect(prettyName('Iran Do Espirito Santo')).toEqual('Iran Do Espirito Santo');
		expect(prettyName('Jacques L\'Huillier')).toEqual('Jacques L\'Huillier');
		expect(prettyName('Peter Le Lievre')).toEqual('Peter Le Lievre');
		expect(prettyName('Ricardo de Los Rios')).toEqual('Ricardo de Los Rios');
		expect(prettyName('Pham an Hai')).toEqual('Pham an Hai');
		expect(prettyName('Shaikh Zayn-Al-Din')).toEqual('Shaikh Zayn-Al-Din');
		expect(prettyName('Gaston Le Beuze')).toEqual('Gaston Le Beuze');
		expect(prettyName('Lu Hsien Ming')).toEqual('Lu Hsien Ming');
		expect(prettyName('Van der Werff')).toEqual('Van der Werff');
		expect(prettyName('Van Son')).toEqual('Van Son');
		expect(prettyName('Byun Jong-Ha')).toEqual('Byun Jong-Ha');
		expect(prettyName('Attributed to Eustache Le Sueur')).toEqual('Attributed to Eustache Le Sueur');
		expect(prettyName('Armand Le Veel')).toEqual('Armand Le Veel');
		expect(prettyName('Jose Antonio Hernandez-Diez')).toEqual('Jose Antonio Hernandez-Diez');
		expect(prettyName('Jan ten Kate')).toEqual('Jan ten Kate');
		expect(prettyName('Michele della Valle')).toEqual('Michele della Valle');
		expect(prettyName('Ng Po Wan')).toEqual('Ng Po Wan');
		expect(prettyName('Kang Yo-Bae')).toEqual('Kang Yo-Bae');
		expect(prettyName('Koch & Bergfeld Silverware Manufactory')).toEqual('Koch & Bergfeld Silverware Manufactory');
		expect(prettyName('Dora de Larios')).toEqual('Dora de Larios');
		expect(prettyName('Et Al')).toEqual('Et Al');
		expect(prettyName('Van Hier')).toEqual('Van Hier');
		expect(prettyName('Ten Kate')).toEqual('Ten Kate');
		expect(prettyName('Xu Ju\'An')).toEqual('Xu Ju\'An');
		expect(prettyName('Ahmed Ben Driss el Yacoubi')).toEqual('Ahmed Ben Driss el Yacoubi');
		expect(prettyName('Constantin Le Roux')).toEqual('Constantin Le Roux');
		expect(prettyName('Byun Shi-Ji')).toEqual('Byun Shi-Ji');
		expect(prettyName('Bernard Le Petit')).toEqual('Bernard Le Petit');
		expect(prettyName('Bernard Le Quellec')).toEqual('Bernard Le Quellec');
		expect(prettyName('Jan Le Witt')).toEqual('Jan Le Witt');
		expect(prettyName('Lee Ha-Eung')).toEqual('Lee Ha-Eung');
		expect(prettyName('N\'Guyen Phan Chanh')).toEqual('N\'Guyen Phan Chanh');
		expect(prettyName('James Baldwin')).toEqual('James Baldwin');
		expect(prettyName('Dia Al-Azzawi')).toEqual('Dia Al-Azzawi');
		expect(prettyName('Henri Cros')).toEqual('Henri Cros');
		expect(prettyName('Gabriel-Jacques de Saint-Aubin')).toEqual('Gabriel-Jacques de Saint-Aubin');
		expect(prettyName('Errol John Le Cain')).toEqual('Errol John Le Cain');
		expect(prettyName('Van Aelst')).toEqual('Van Aelst');
		expect(prettyName('Van Wyk')).toEqual('Van Wyk');
		expect(prettyName('Tony d\'Amico')).toEqual('Tony d\'Amico');
		expect(prettyName('Yoon Jung-Sik')).toEqual('Yoon Jung-Sik');
		expect(prettyName('John Le Conte')).toEqual('John Le Conte');
		expect(prettyName('Hwang Young-Sung')).toEqual('Hwang Young-Sung');
		expect(prettyName('Herman von Le Suire')).toEqual('Herman von Le Suire');
		expect(prettyName('Agiselo Antonio Don Palomino de Castro y Velasco')).toEqual('Agiselo Antonio Don Palomino de Castro y Velasco');
		expect(prettyName('Alain Le Nost')).toEqual('Alain Le Nost');
		expect(prettyName('Ernst Te Peerdt')).toEqual('Ernst Te Peerdt');
		expect(prettyName('Etienne Le Rallic')).toEqual('Etienne Le Rallic');
		expect(prettyName('Gerrit van \'T Net')).toEqual('Gerrit van \'T Net');
		expect(prettyName('Willy ter Hell')).toEqual('Willy ter Hell');
		expect(prettyName('Van Loo')).toEqual('Van Loo');
		expect(prettyName('Carel Nicolaas Storm van S\'Gravensande')).toEqual('Carel Nicolaas Storm van S\'Gravensande');
		expect(prettyName('Chang Chen-Yu')).toEqual('Chang Chen-Yu');
		expect(prettyName('De Keyser')).toEqual('De Keyser');
		expect(prettyName('De Wit')).toEqual('De Wit');
		expect(prettyName('Le Sage')).toEqual('Le Sage');
		expect(prettyName('Jean Baptiste Joseph Le Tellier')).toEqual('Jean Baptiste Joseph Le Tellier');
		expect(prettyName('Philip van Brunt')).toEqual('Philip van Brunt');
		expect(prettyName('Stephane Le Grec')).toEqual('Stephane Le Grec');
		expect(prettyName('Alejandro de Riquer E Inglada')).toEqual('Alejandro de Riquer E Inglada');
		expect(prettyName('Shiy de-Jinn')).toEqual('Shiy de-Jinn');
		expect(prettyName('Hatsuyama Shigeru')).toEqual('Hatsuyama Shigeru');
		expect(prettyName('El Seed')).toEqual('El Seed');
		expect(prettyName('Eveline Le Mouel')).toEqual('Eveline Le Mouel');
		expect(prettyName('H ten Hoven')).toEqual('H ten Hoven');
		expect(prettyName('Van der Helst')).toEqual('Van der Helst');
		expect(prettyName('Laurent Le Pont')).toEqual('Laurent Le Pont');
		expect(prettyName('Master of the Annunciation to the Shepherds')).toEqual('Master of the Annunciation to the Shepherds');
		expect(prettyName('Julien Le Blant')).toEqual('Julien Le Blant');
		expect(prettyName('Louis Le Breton')).toEqual('Louis Le Breton');
		expect(prettyName('Attributed to Thorvald Hagedorn-Olsen')).toEqual('Attributed to Thorvald Hagedorn-Olsen');
		expect(prettyName('Cai Tianxiong')).toEqual('Cai Tianxiong');
		expect(prettyName('De Troy')).toEqual('De Troy');
		expect(prettyName('Jet-Te Ranning')).toEqual('Jet-Te Ranning');
		expect(prettyName('Hendrik ten Oever')).toEqual('Hendrik ten Oever');
		expect(prettyName('Park No-Soo')).toEqual('Park No-Soo');
		expect(prettyName('Robert de Vaugondy')).toEqual('Robert de Vaugondy');
		expect(prettyName('Rosina Becker Do Valle')).toEqual('Rosina Becker Do Valle');
		expect(prettyName('Pierre Le Colas')).toEqual('Pierre Le Colas');
		expect(prettyName('Kay Fisker')).toEqual('Kay Fisker');
		expect(prettyName('Pyon Kwansik')).toEqual('Pyon Kwansik');
		expect(prettyName('Georges Le Poitevin')).toEqual('Georges Le Poitevin');
		expect(prettyName('Giovanni dell\'Acqua')).toEqual('Giovanni dell\'Acqua');
		expect(prettyName('Eugene Leon L\'Hoest')).toEqual('Eugene Leon L\'Hoest');
		expect(prettyName('Louis Le Sueur')).toEqual('Louis Le Sueur');
		expect(prettyName('Linda Le Kinff')).toEqual('Linda Le Kinff');
		expect(prettyName('Attributed to Louis Joseph Le Lorrain')).toEqual('Attributed to Louis Joseph Le Lorrain');
		expect(prettyName('Attributed to Tommaso d\'Antonio Manzuoli')).toEqual('Attributed to Tommaso d\'Antonio Manzuoli');
		expect(prettyName('Follower of Peter Le Cave')).toEqual('Follower of Peter Le Cave');
		expect(prettyName('Benoit Le Coffre')).toEqual('Benoit Le Coffre');
		expect(prettyName('Chen an Jian')).toEqual('Chen an Jian');
		expect(prettyName('Hannes d\'Haese')).toEqual('Hannes d\'Haese');
		expect(prettyName('Jeremy Le Grice')).toEqual('Jeremy Le Grice');
		expect(prettyName('School of Van Ostade')).toEqual('School of Van Ostade');
		expect(prettyName('Gilbert de Keyser')).toEqual('Gilbert de Keyser');
		expect(prettyName('Le Carre')).toEqual('Le Carre');
		expect(prettyName('Le Cave')).toEqual('Le Cave');
		expect(prettyName('Lee Joong-Seop')).toEqual('Lee Joong-Seop');
		expect(prettyName('Leung Kui-Ting')).toEqual('Leung Kui-Ting');
		expect(prettyName('Joseph la Piana')).toEqual('Joseph la Piana');
		expect(prettyName('Georges Le Mare')).toEqual('Georges Le Mare');
		expect(prettyName('Elena Hel\'R')).toEqual('Elena Hel\'R');
		expect(prettyName('Van Bredael')).toEqual('Van Bredael');
		expect(prettyName('Van der Straeten')).toEqual('Van der Straeten');
		expect(prettyName('Van Zeebroeck')).toEqual('Van Zeebroeck');
		expect(prettyName('Ahn Chang-Hong')).toEqual('Ahn Chang-Hong');
		expect(prettyName('Christian Kratzenstein-Stub')).toEqual('Christian Kratzenstein-Stub');
		expect(prettyName('Charles A de L\'Aubiniere')).toEqual('Charles A de L\'Aubiniere');
		expect(prettyName('John van\'T Slot')).toEqual('John van\'T Slot');
		expect(prettyName('Philip Le Bas')).toEqual('Philip Le Bas');
		expect(prettyName('Pietro di Francesco degli Orioli')).toEqual('Pietro di Francesco degli Orioli');
		expect(prettyName('Son Sang-Ki')).toEqual('Son Sang-Ki');
		expect(prettyName('Min Kyung-Kap')).toEqual('Min Kyung-Kap');
		expect(prettyName('Li Chun-Shan')).toEqual('Li Chun-Shan');
		expect(prettyName('Attributed to Jacob Isacksz van Ruisdael')).toEqual('Attributed to Jacob Isacksz van Ruisdael');
		expect(prettyName('Gerard Le Nabasque')).toEqual('Gerard Le Nabasque');
		expect(prettyName('After Pierre Le Faguays')).toEqual('After Pierre Le Faguays');
		expect(prettyName('Xing Cheng\'Ai')).toEqual('Xing Cheng\'Ai');
		expect(prettyName('Julien T\'Felt')).toEqual('Julien T\'Felt');
		expect(prettyName('Van Blarenberghe')).toEqual('Van Blarenberghe');
		expect(prettyName('Van de Venne')).toEqual('Van de Venne');
		expect(prettyName('Van der Heyden')).toEqual('Van der Heyden');
		expect(prettyName('Van der Venne')).toEqual('Van der Venne');
		expect(prettyName('Tran van Ha')).toEqual('Tran van Ha');
		expect(prettyName('Attributed to Sauveur Le Conte')).toEqual('Attributed to Sauveur Le Conte');
		expect(prettyName('Jacques Le Chevalier')).toEqual('Jacques Le Chevalier');
		expect(prettyName('Jan Te Wierik')).toEqual('Jan Te Wierik');
		expect(prettyName('Hatem el-Mekki')).toEqual('Hatem el-Mekki');
		expect(prettyName('Henri Le Hon')).toEqual('Henri Le Hon');
		expect(prettyName('Jean Pierre Le Bras')).toEqual('Jean Pierre Le Bras');
		expect(prettyName('Jehan Le Liepvre')).toEqual('Jehan Le Liepvre');
		expect(prettyName('Lee Man-Ik')).toEqual('Lee Man-Ik');
		expect(prettyName('Lu Yi-Fei')).toEqual('Lu Yi-Fei');
		expect(prettyName('Ryu Kyung-Chai')).toEqual('Ryu Kyung-Chai');
		expect(prettyName('Pierre Le Boueff')).toEqual('Pierre Le Boueff');
		expect(prettyName('Pierre Le Tan')).toEqual('Pierre Le Tan');
		expect(prettyName('Nishiyama Kan\'Ei')).toEqual('Nishiyama Kan\'Ei');
		expect(prettyName('Attributed to Van Balen')).toEqual('Attributed to Van Balen');
		expect(prettyName('Philippe Le Tellier')).toEqual('Philippe Le Tellier');
		expect(prettyName('John Gossage')).toEqual('John Gossage');
		expect(prettyName('James A. Porter (1905 - 1970)')).toEqual('James A. Porter (1905 - 1970)');
		expect(prettyName('Alexandre Le Bihan')).toEqual('Alexandre Le Bihan');
		expect(prettyName('Anne Mie van Kerckhoven')).toEqual('Anne Mie van Kerckhoven');
		expect(prettyName('Antonio d\'Agostino')).toEqual('Antonio d\'Agostino');
		expect(prettyName('Francis Le Coadic')).toEqual('Francis Le Coadic');
		expect(prettyName('Yoon Young-Ja')).toEqual('Yoon Young-Ja');
		expect(prettyName('Pascual di Bianco')).toEqual('Pascual di Bianco');
		expect(prettyName('Claude Le Boul')).toEqual('Claude Le Boul');
		expect(prettyName('Dino la Bianca')).toEqual('Dino la Bianca');
		expect(prettyName('Mappin and Webb LTD')).toEqual('Mappin and Webb LTD');
		expect(prettyName('Leon Jules Alphonse Le Royer')).toEqual('Leon Jules Alphonse Le Royer');
		expect(prettyName('Leon Le Goache de Belle')).toEqual('Leon Le Goache de Belle');
		expect(prettyName('Mohamed el-Baz')).toEqual('Mohamed el-Baz');
		expect(prettyName('Imad Al-Hassani')).toEqual('Imad Al-Hassani');
		expect(prettyName('Jan de vos IV')).toEqual('Jan de vos IV');
		expect(prettyName('Pierre d\'Avesn')).toEqual('Pierre d\'Avesn');
		expect(prettyName('Pierre Joseph Le Mettais')).toEqual('Pierre Joseph Le Mettais');
		expect(prettyName('Shim Sa-Jeong')).toEqual('Shim Sa-Jeong');
		expect(prettyName('Paran G\'Schrey')).toEqual('Paran G\'Schrey');
		expect(prettyName('Park Saeng-Kwang')).toEqual('Park Saeng-Kwang');
		expect(prettyName('Arthur d\'Auvergne Boxall')).toEqual('Arthur d\'Auvergne Boxall');
		expect(prettyName('Alessandro d\'Ambrosio')).toEqual('Alessandro d\'Ambrosio');
		expect(prettyName('After Van Ostade')).toEqual('After Van Ostade');
		expect(prettyName('Gleb Bogomolov')).toEqual('Gleb Bogomolov');
		expect(prettyName('Tam van Tran')).toEqual('Tam van Tran');
		expect(prettyName('Ernest Race')).toEqual('Ernest Race');
		expect(prettyName('Lee Dongyoub')).toEqual('Lee Dongyoub');
		expect(prettyName('Maerten de Vos')).toEqual('Maerten de Vos');
		expect(prettyName('Andre Courreges')).toEqual('Andre Courreges');
		expect(prettyName('Dave Heath')).toEqual('Dave Heath');
		expect(prettyName('Wen Ding')).toEqual('Wen Ding');
		expect(prettyName('Gerard Le Cloarec')).toEqual('Gerard Le Cloarec');
		expect(prettyName('E Le Bienvenu-Dutourp')).toEqual('E Le Bienvenu-Dutourp');
		expect(prettyName('Van Britten')).toEqual('Van Britten');
		expect(prettyName('Van Dongen')).toEqual('Van Dongen');
		expect(prettyName('Van Spaendonck')).toEqual('Van Spaendonck');
		expect(prettyName('Studio of Van der Meulen')).toEqual('Studio of Van der Meulen');
		expect(prettyName('Lee Seungjio')).toEqual('Lee Seungjio');
		expect(prettyName('Louis Le Bail')).toEqual('Louis Le Bail');
		expect(prettyName('Ma Qi\'Ou')).toEqual('Ma Qi\'Ou');
		expect(prettyName('Marion Tuu\'Luuq')).toEqual('Marion Tuu\'Luuq');
		expect(prettyName('Kuo Wei-Kuo')).toEqual('Kuo Wei-Kuo');
		expect(prettyName('Celestin Francois Nanteuil-Leboeuf')).toEqual('Celestin Francois Nanteuil-Leboeuf');
		expect(prettyName('Hasso von Winning')).toEqual('Hasso von Winning');
		expect(prettyName('Hendrik Jan ten Cate')).toEqual('Hendrik Jan ten Cate');
		expect(prettyName('Jesus Maria de Las Casas')).toEqual('Jesus Maria de Las Casas');
		expect(prettyName('Joe d\'Urso')).toEqual('Joe d\'Urso');
		expect(prettyName('Jacques Le Nantec')).toEqual('Jacques Le Nantec');
		expect(prettyName('Attributed to Henri Le Sidaner')).toEqual('Attributed to Henri Le Sidaner');
		expect(prettyName('Arthur van Zile Bodwell')).toEqual('Arthur van Zile Bodwell');
		expect(prettyName('Andy Leleisi\'Uao')).toEqual('Andy Leleisi\'Uao');
		expect(prettyName('Attributed to De Simone')).toEqual('Attributed to De Simone');
		expect(prettyName('Park Youngsun')).toEqual('Park Youngsun');
		expect(prettyName('Percy van Eman Ivory')).toEqual('Percy van Eman Ivory');
		expect(prettyName('Pierluca degli Innocenti')).toEqual('Pierluca degli Innocenti');
		expect(prettyName('Piero Dalle Ceste')).toEqual('Piero Dalle Ceste');
		expect(prettyName('Riza-I Abbasi')).toEqual('Riza-I Abbasi');
		expect(prettyName('Rouben ter-Arutunian')).toEqual('Rouben ter-Arutunian');
		expect(prettyName('Neville Le Ray')).toEqual('Neville Le Ray');
		expect(prettyName('Raja Shahriman Bin Raza Aziddin')).toEqual('Raja Shahriman Bin Raza Aziddin');
		expect(prettyName('Ryoo Byung-Yup')).toEqual('Ryoo Byung-Yup');
		expect(prettyName('School of Van der Meulen')).toEqual('School of Van der Meulen');
		expect(prettyName('Joseph Vogel')).toEqual('Joseph Vogel');
		expect(prettyName('Chiu Ya-Tsai')).toEqual('Chiu Ya-Tsai');
		expect(prettyName('Ma Tai')).toEqual('Ma Tai');
		expect(prettyName('Lewis van Dercar')).toEqual('Lewis van Dercar');
		expect(prettyName('A George I Silver Caster')).toEqual('A George I Silver Caster');
		expect(prettyName('Sofronio Y Mendoza')).toEqual('Sofronio Y Mendoza');
		expect(prettyName('Ferdinand Le Feubure')).toEqual('Ferdinand Le Feubure');
		expect(prettyName('Kson Cp5')).toEqual('Kson Cp5');
		expect(prettyName('Louis Joseph Le Lorrain')).toEqual('Louis Joseph Le Lorrain');
		expect(prettyName('Ludwig ten Hompel')).toEqual('Ludwig ten Hompel');
		expect(prettyName('Liao Yu-An')).toEqual('Liao Yu-An');
		expect(prettyName('Joseph Marie Le Tournier')).toEqual('Joseph Marie Le Tournier');
		expect(prettyName('Gruppe Brand')).toEqual('Gruppe Brand');
		expect(prettyName('Van de Sande Bakhuyzen')).toEqual('Van de Sande Bakhuyzen');
		expect(prettyName('Van der Myn')).toEqual('Van der Myn');
		expect(prettyName('Van der Poel')).toEqual('Van der Poel');
		expect(prettyName('Van Leyden')).toEqual('Van Leyden');
		expect(prettyName('VLP (Vive la Peinture)')).toEqual('VLP (Vive la Peinture)');
		expect(prettyName('Wim ten Broek')).toEqual('Wim ten Broek');
		expect(prettyName('Zaccaria dal Bo')).toEqual('Zaccaria dal Bo');
		expect(prettyName('Bernhard Schneider-Blumberg')).toEqual('Bernhard Schneider-Blumberg');
		expect(prettyName('Charles D’orville Pilkington Jackson')).toEqual('Charles D’orville Pilkington Jackson');
		expect(prettyName('Attributed to Peter Le Cave')).toEqual('Attributed to Peter Le Cave');
		expect(prettyName('Claude Le Baube')).toEqual('Claude Le Baube');
		expect(prettyName('Claudio d\'Angelo')).toEqual('Claudio d\'Angelo');
		expect(prettyName('Follower of De Heem')).toEqual('Follower of De Heem');
		expect(prettyName('Anthony de Bernardin')).toEqual('Anthony de Bernardin');
		expect(prettyName('J Nelson Drummond')).toEqual('J Nelson Drummond');
		expect(prettyName('Herve & Richard di Rosa')).toEqual('Herve & Richard di Rosa');
		expect(prettyName('Jacob ten Hagen')).toEqual('Jacob ten Hagen');
		expect(prettyName('Jean-Pierre Le Bozec')).toEqual('Jean-Pierre Le Bozec');
		expect(prettyName('Phillip Evergood')).toEqual('Phillip Evergood');
		expect(prettyName('Rose Sommer-Leypold')).toEqual('Rose Sommer-Leypold');
		expect(prettyName('Park Hang-Ryul')).toEqual('Park Hang-Ryul');
		expect(prettyName('SPanish-Philippino School')).toEqual('SPanish-Philippino School');
		expect(prettyName('Rene Le Saec')).toEqual('Rene Le Saec');
		expect(prettyName('Joel Peter Witkin')).toEqual('Joel Peter Witkin');
		expect(prettyName('Gonsalvo Carelli')).toEqual('Gonsalvo Carelli');
		expect(prettyName('Rong Rong & Inri')).toEqual('Rong Rong & Inri');
		expect(prettyName('Yi Sangbom')).toEqual('Yi Sangbom');
		expect(prettyName('Joseph Le Tessier')).toEqual('Joseph Le Tessier');
		expect(prettyName('Jules Maurice Le Natur')).toEqual('Jules Maurice Le Natur');
		expect(prettyName('Kano Seisen\'In')).toEqual('Kano Seisen\'In');
		expect(prettyName('Kwun Sun-Cheol')).toEqual('Kwun Sun-Cheol');
		expect(prettyName('Mathvei Kogan-Shats')).toEqual('Mathvei Kogan-Shats');
		expect(prettyName('Mellerio Dits Meller')).toEqual('Mellerio Dits Meller');
		expect(prettyName('Maria Hofker-Rueter')).toEqual('Maria Hofker-Rueter');
		expect(prettyName('Lee Shi-Chi')).toEqual('Lee Shi-Chi');
		expect(prettyName('Li Di')).toEqual('Li Di');
		expect(prettyName('Ernesto Soler de Las Casas')).toEqual('Ernesto Soler de Las Casas');
		expect(prettyName('Gaspard Le Marchant Tupper')).toEqual('Gaspard Le Marchant Tupper');
		expect(prettyName('Flore Vindevogel')).toEqual('Flore Vindevogel');
		expect(prettyName('Yahne Le Toumelin')).toEqual('Yahne Le Toumelin');
		expect(prettyName('Therese Ruffie-de Longueval')).toEqual('Therese Ruffie-de Longueval');
		expect(prettyName('Irene Le Goaster')).toEqual('Irene Le Goaster');
		expect(prettyName('After Van Huysum')).toEqual('After Van Huysum');
		expect(prettyName('Andre Le Moigne')).toEqual('Andre Le Moigne');
		expect(prettyName('Adolphe Etienne Viollet-Le-Duc the Younger')).toEqual('Adolphe Etienne Viollet-Le-Duc the Younger');
		expect(prettyName('Attributed to Jean Baptiste Le Paon')).toEqual('Attributed to Jean Baptiste Le Paon');
		expect(prettyName('Attributed to Angelo Dall\'Oca Bianca')).toEqual('Attributed to Angelo Dall\'Oca Bianca');
		expect(prettyName('Barbara van Stappen')).toEqual('Barbara van Stappen');
		expect(prettyName('Carlo d\'Orta')).toEqual('Carlo d\'Orta');
		expect(prettyName('Chang Chih-Chen')).toEqual('Chang Chih-Chen');
		expect(prettyName('De la Hyre')).toEqual('De la Hyre');
		expect(prettyName('De Luca')).toEqual('De Luca');
		expect(prettyName('Cho Seok-Jin')).toEqual('Cho Seok-Jin');
		expect(prettyName('Follower of Tommaso d\'Antonio Manzuoli')).toEqual('Follower of Tommaso d\'Antonio Manzuoli');
		expect(prettyName('Follower of Van de Velde')).toEqual('Follower of Van de Velde');
		expect(prettyName('Aurelia della Corte Szvatek')).toEqual('Aurelia della Corte Szvatek');
		expect(prettyName('Carlo d\'Aloisio da Vasto')).toEqual('Carlo d\'Aloisio da Vasto');
		expect(prettyName('De Critz')).toEqual('De Critz');
		expect(prettyName('De Vito')).toEqual('De Vito');
		expect(prettyName('De Vries')).toEqual('De Vries');
		expect(prettyName('Chon Byung-Hyun')).toEqual('Chon Byung-Hyun');
		expect(prettyName('Jimmy de Sana')).toEqual('Jimmy de Sana');
		expect(prettyName('Renee de Wet Le Roux')).toEqual('Renee de Wet Le Roux');
		expect(prettyName('Roger Vanden Abbeele')).toEqual('Roger Vanden Abbeele');
		expect(prettyName('Philippe Le Clerc')).toEqual('Philippe Le Clerc');
		expect(prettyName('Le van De')).toEqual('Le van De');
		expect(prettyName('Karl Friedrich Le Feubure')).toEqual('Karl Friedrich Le Feubure');
		expect(prettyName('Bae Bienu')).toEqual('Bae Bienu');
		expect(prettyName('Jean Joseph Martin')).toEqual('Jean Joseph Martin');
		expect(prettyName('Gerard Le Nalbaut')).toEqual('Gerard Le Nalbaut');
		expect(prettyName('Eydum Av Reyni')).toEqual('Eydum Av Reyni');
		expect(prettyName('Francis William Synge Le Maistre')).toEqual('Francis William Synge Le Maistre');
		expect(prettyName('Gerolamo Dai Libri')).toEqual('Gerolamo Dai Libri');
		expect(prettyName('After Pierre-Paul Prud\'Hon')).toEqual('After Pierre-Paul Prud\'Hon');
		expect(prettyName('Alfred di Cesare')).toEqual('Alfred di Cesare');
		expect(prettyName('Amin el-Bacha')).toEqual('Amin el-Bacha');
		expect(prettyName('Van der Does')).toEqual('Van der Does');
		expect(prettyName('Van der Lamen')).toEqual('Van der Lamen');
		expect(prettyName('Thomas Le Hardy')).toEqual('Thomas Le Hardy');
		expect(prettyName('Tjarko ten Have')).toEqual('Tjarko ten Have');
		expect(prettyName('Pasquale de Antonis')).toEqual('Pasquale de Antonis');
		expect(prettyName('Ibrahim Pur-Abbas')).toEqual('Ibrahim Pur-Abbas');
		expect(prettyName('Follower of Van Os')).toEqual('Follower of Van Os');
		expect(prettyName('Yves de la Tour d\'Auvergne')).toEqual('Yves de la Tour d\'Auvergne');
		expect(prettyName('Teng Pu-Chun')).toEqual('Teng Pu-Chun');
		expect(prettyName('The Goldsmiths & Silversmiths Co LTD')).toEqual('The Goldsmiths & Silversmiths Co LTD');
		expect(prettyName('Tran van Tho')).toEqual('Tran van Tho');
		expect(prettyName('Van den Burch')).toEqual('Van den Burch');
		expect(prettyName('Charles Edouard Crespi-Le-Prince')).toEqual('Charles Edouard Crespi-Le-Prince');
		expect(prettyName('Begga d\'Haese')).toEqual('Begga d\'Haese');
		expect(prettyName('Bouchta el Hayani')).toEqual('Bouchta el Hayani');
		expect(prettyName('De Witt')).toEqual('De Witt');
		expect(prettyName('Huang Min-Jun')).toEqual('Huang Min-Jun');
		expect(prettyName('Jon d\'Orazio')).toEqual('Jon d\'Orazio');
		expect(prettyName('Jose Maria Arenas de Los Martires')).toEqual('Jose Maria Arenas de Los Martires');
		expect(prettyName('Jang Seung-Eop')).toEqual('Jang Seung-Eop');
		expect(prettyName('Marie Nestler-Laux')).toEqual('Marie Nestler-Laux');
		expect(prettyName('Le Flohic')).toEqual('Le Flohic');
		expect(prettyName('Le Moyne')).toEqual('Le Moyne');
		expect(prettyName('Juan de Las Roelas')).toEqual('Juan de Las Roelas');
		expect(prettyName('Kim Hong-Do')).toEqual('Kim Hong-Do');
		expect(prettyName('Kwak Duck-Jun')).toEqual('Kwak Duck-Jun');
		expect(prettyName('Michele-Eudes de L\'Hay')).toEqual('Michele-Eudes de L\'Hay');
		expect(prettyName('Rhee Da')).toEqual('Rhee Da');
		expect(prettyName('School of Van de Velde')).toEqual('School of Van de Velde');
		expect(prettyName('Philippe Le Molt')).toEqual('Philippe Le Molt');
		expect(prettyName('Sharon Ya\'Ari')).toEqual('Sharon Ya\'Ari');
		expect(prettyName('Park Deuk-Soon')).toEqual('Park Deuk-Soon');
		expect(prettyName('Liu Shih-Tung')).toEqual('Liu Shih-Tung');
		expect(prettyName('Crash (John Matos)')).toEqual('Crash (John Matos)');
		expect(prettyName('Lu Shengzhong')).toEqual('Lu Shengzhong');
		expect(prettyName('Barbara van Cleve')).toEqual('Barbara van Cleve');
		expect(prettyName('François Craenhals')).toEqual('François Craenhals');
		expect(prettyName('Attributed to Jan Le Ducq')).toEqual('Attributed to Jan Le Ducq');
		expect(prettyName('Anton Ruzicka-Lautenschlager')).toEqual('Anton Ruzicka-Lautenschlager');
		expect(prettyName('Friederike von Rauch')).toEqual('Friederike von Rauch');
		expect(prettyName('Egidio Dall\'Oglio')).toEqual('Egidio Dall\'Oglio');
		expect(prettyName('Egon Moller-Nielsen')).toEqual('Egon Moller-Nielsen');
		expect(prettyName('Gabrielle dell\'Otto')).toEqual('Gabrielle dell\'Otto');
		expect(prettyName('Gadal\'Miny Munyarryun')).toEqual('Gadal\'Miny Munyarryun');
		expect(prettyName('Giorgio Lo Fermo')).toEqual('Giorgio Lo Fermo');
		expect(prettyName('Felix Morel-Lamy')).toEqual('Felix Morel-Lamy');
		expect(prettyName('Franco-Italian School')).toEqual('Franco-Italian School');
		expect(prettyName('Francesco d\'Arena')).toEqual('Francesco d\'Arena');
		expect(prettyName('Ex de Medici')).toEqual('Ex de Medici');
		expect(prettyName('Van der Meer')).toEqual('Van der Meer');
		expect(prettyName('Walid el Masri')).toEqual('Walid el Masri');
		expect(prettyName('William Abraham Le Mesurier')).toEqual('William Abraham Le Mesurier');
		expect(prettyName('Follower of Van Huysum')).toEqual('Follower of Van Huysum');
		expect(prettyName('The Shop of the Crafters')).toEqual('The Shop of the Crafters');
		expect(prettyName('Theo L\'Herminez')).toEqual('Theo L\'Herminez');
		expect(prettyName('Sung Paikjoo')).toEqual('Sung Paikjoo');
		expect(prettyName('David Le Clerc')).toEqual('David Le Clerc');
		expect(prettyName('De Brusses')).toEqual('De Brusses');
		expect(prettyName('De Heusch')).toEqual('De Heusch');
		expect(prettyName('De Kat')).toEqual('De Kat');
		expect(prettyName('De la Roche')).toEqual('De la Roche');
		expect(prettyName('De Smet')).toEqual('De Smet');
		expect(prettyName('Dinh Q Le')).toEqual('Dinh Q Le');
		expect(prettyName('Ch\'Ng Huck Theng')).toEqual('Ch\'Ng Huck Theng');
		expect(prettyName('Follower of Van Kessel')).toEqual('Follower of Van Kessel');
		expect(prettyName('Brian Travers-Smith')).toEqual('Brian Travers-Smith');
		expect(prettyName('Bruno di Maio')).toEqual('Bruno di Maio');
		expect(prettyName('Lurelle van Arsdale Guild')).toEqual('Lurelle van Arsdale Guild');
		expect(prettyName('Liliane Silva Le Fur')).toEqual('Liliane Silva Le Fur');
		expect(prettyName('Jupp Dernbach-Mayen')).toEqual('Jupp Dernbach-Mayen');
		expect(prettyName('Just L\'Hernault')).toEqual('Just L\'Hernault');
		expect(prettyName('Karol Wierusz-Kowalski')).toEqual('Karol Wierusz-Kowalski');
		expect(prettyName('How & Nosm')).toEqual('How & Nosm');
		expect(prettyName('Hanna Bekker Vom Rath')).toEqual('Hanna Bekker Vom Rath');
		expect(prettyName('Jane Le Soudier')).toEqual('Jane Le Soudier');
		expect(prettyName('Jaune Quick-to-See Smith')).toEqual('Jaune Quick-to-See Smith');
		expect(prettyName('Pauline Caron-Langlois')).toEqual('Pauline Caron-Langlois');
		expect(prettyName('Nicholas de Wael')).toEqual('Nicholas de Wael');
		expect(prettyName('Octave Penguilly-L\'Haridon')).toEqual('Octave Penguilly-L\'Haridon');
		expect(prettyName('Sara H Le Jeune')).toEqual('Sara H Le Jeune');
		expect(prettyName('Simone Le Carre-Galimard')).toEqual('Simone Le Carre-Galimard');
		expect(prettyName('Pierre Le Sage')).toEqual('Pierre Le Sage');
		expect(prettyName('Attributed to Jacques Le Moyne')).toEqual('Attributed to Jacques Le Moyne');
		expect(prettyName('Alphonse la Paglia')).toEqual('Alphonse la Paglia');
		expect(prettyName('Amleto dalla Costa')).toEqual('Amleto dalla Costa');
		expect(prettyName('Arthur Eden-Sillenstede')).toEqual('Arthur Eden-Sillenstede');
		expect(prettyName('Anglo-Italian School')).toEqual('Anglo-Italian School');
		expect(prettyName('Thierry Le Goues')).toEqual('Thierry Le Goues');
		expect(prettyName('Evan de Vilde')).toEqual('Evan de Vilde');
		expect(prettyName('Rimma Gerlovina and Valeriy Gerlovin')).toEqual('Rimma Gerlovina and Valeriy Gerlovin');
		expect(prettyName('Abbott van Dada')).toEqual('Abbott van Dada');
		expect(prettyName('Huang Liuzi')).toEqual('Huang Liuzi');
		expect(prettyName('A Higo Tsuba')).toEqual('A Higo Tsuba');
		expect(prettyName('Guo Bochuan')).toEqual('Guo Bochuan');
		expect(prettyName('Vereinigte Werkstatten Fur Kunst Im Handwerk')).toEqual('Vereinigte Werkstatten Fur Kunst Im Handwerk');
		expect(prettyName('Fernando Ferreira de Araujo')).toEqual('Fernando Ferreira de Araujo');
		expect(prettyName('Beth Lipman')).toEqual('Beth Lipman');
		expect(prettyName('David de Noter')).toEqual('David de Noter');
		expect(prettyName('James White and Tim Sheward')).toEqual('James White and Tim Sheward');
		expect(prettyName('Takuma Nakahira')).toEqual('Takuma Nakahira');
		expect(prettyName('Lee Jeonglok')).toEqual('Lee Jeonglok');
		expect(prettyName('Giovanni Paolo Castelli')).toEqual('Giovanni Paolo Castelli');
		expect(prettyName('Eric and Heather Chanschatz')).toEqual('Eric and Heather Chanschatz');
		expect(prettyName('Giovanni del Biondo dal Casentino')).toEqual('Giovanni del Biondo dal Casentino');
		expect(prettyName('Le Dien')).toEqual('Le Dien');
		expect(prettyName('Serge van Khache')).toEqual('Serge van Khache');
		expect(prettyName('Giovanni Benedetto Castiglione Detto il Grecchetto')).toEqual('Giovanni Benedetto Castiglione Detto il Grecchetto');
		expect(prettyName('Van Aken')).toEqual('Van Aken');
		expect(prettyName('Van der Croos')).toEqual('Van der Croos');
		expect(prettyName('Van der Voort')).toEqual('Van der Voort');
		expect(prettyName('Victor Le Gentile')).toEqual('Victor Le Gentile');
		expect(prettyName('Vincent di Fate')).toEqual('Vincent di Fate');
		expect(prettyName('Volkstedt Porcelain Manufactory')).toEqual('Volkstedt Porcelain Manufactory');
		expect(prettyName('Studio of Van Loo')).toEqual('Studio of Van Loo');
		expect(prettyName('Follower of Van Ostade')).toEqual('Follower of Van Ostade');
		expect(prettyName('Saleh Al-Jumaie')).toEqual('Saleh Al-Jumaie');
		expect(prettyName('Imre von Santho')).toEqual('Imre von Santho');
		expect(prettyName('Tzu-Kuey Sheu')).toEqual('Tzu-Kuey Sheu');
		expect(prettyName('Kobe de Peuter')).toEqual('Kobe de Peuter');
		expect(prettyName('La Fargue')).toEqual('La Fargue');
		expect(prettyName('Lang Ping-Cheng')).toEqual('Lang Ping-Cheng');
		expect(prettyName('Louis John de Donato')).toEqual('Louis John de Donato');
		expect(prettyName('Louis Le Camus')).toEqual('Louis Le Camus');
		expect(prettyName('Manuel d\'Rugama')).toEqual('Manuel d\'Rugama');
		expect(prettyName('Marc Le Mene')).toEqual('Marc Le Mene');
		expect(prettyName('Jumana el Husseini')).toEqual('Jumana el Husseini');
		expect(prettyName('Kareem el Qurity')).toEqual('Kareem el Qurity');
		expect(prettyName('De Hooch')).toEqual('De Hooch');
		expect(prettyName('De Lamare')).toEqual('De Lamare');
		expect(prettyName('De Meyer')).toEqual('De Meyer');
		expect(prettyName('Catherine di Betta')).toEqual('Catherine di Betta');
		expect(prettyName('Attributed to Mauritz Frederik Hendrick de Haas')).toEqual('Attributed to Mauritz Frederik Hendrick de Haas');
		expect(prettyName('Follower of Van Bloemen')).toEqual('Follower of Van Bloemen');
		expect(prettyName('Follower of Van der Meulen')).toEqual('Follower of Van der Meulen');
		expect(prettyName('Charles-Louis-Francois Le Carpentier')).toEqual('Charles-Louis-Francois Le Carpentier');
		expect(prettyName('Christiaan ten Bruggen Kate')).toEqual('Christiaan ten Bruggen Kate');
		expect(prettyName('Augustine Dall\'Ava')).toEqual('Augustine Dall\'Ava');
		expect(prettyName('Avdei B ter-Oganian')).toEqual('Avdei B ter-Oganian');
		expect(prettyName('Hendrik Gerard ten Hoet')).toEqual('Hendrik Gerard ten Hoet');
		expect(prettyName('Henning Damgaard-Sorensen')).toEqual('Henning Damgaard-Sorensen');
		expect(prettyName('Ibrahim el Dessouki')).toEqual('Ibrahim el Dessouki');
		expect(prettyName('Imane el Makhchouni')).toEqual('Imane el Makhchouni');
		expect(prettyName('Ja\'Bagh Kaghado')).toEqual('Ja\'Bagh Kaghado');
		expect(prettyName('Gustavo Dall\'Ara')).toEqual('Gustavo Dall\'Ara');
		expect(prettyName('Jean Marie Le Guen')).toEqual('Jean Marie Le Guen');
		expect(prettyName('Alfred Le Petit')).toEqual('Alfred Le Petit');
		expect(prettyName('Amalda Hubrecht')).toEqual('Amalda Hubrecht');
		expect(prettyName('Ambroise Charlemagne Victor Le Chenetier')).toEqual('Ambroise Charlemagne Victor Le Chenetier');
		expect(prettyName('Andre E van Opstal')).toEqual('Andre E van Opstal');
		expect(prettyName('Andre Paul Le Roux')).toEqual('Andre Paul Le Roux');
		expect(prettyName('Antoine Le Grand')).toEqual('Antoine Le Grand');
		expect(prettyName('Albert Le Normand')).toEqual('Albert Le Normand');
		expect(prettyName('School of Van Bloemen')).toEqual('School of Van Bloemen');
		expect(prettyName('School of Van Loo')).toEqual('School of Van Loo');
		expect(prettyName('Seong Jae-Hyu')).toEqual('Seong Jae-Hyu');
		expect(prettyName('Prosper Le Courtier')).toEqual('Prosper Le Courtier');
	});
});


